# Generated by Django 5.2.7 on 2025-10-09 18:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referência')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('contato', models.CharField(blank=True, max_length=200, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Base')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('numero_encomenda', models.AutoField(primary_key=True, serialize=False, verbose_name='Número da Encomenda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação (sistema)')),
                ('data_encomenda', models.DateField(default=django.utils.timezone.now, help_text='Data da encomenda (campo do cabeçalho)', verbose_name='Data')),
                ('responsavel_criacao', models.CharField(help_text='Responsável pela criação da encomenda', max_length=100, verbose_name='Responsável')),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('cotacao', 'Em Cotação'), ('aprovada', 'Aprovada'), ('em_andamento', 'Em Andamento'), ('pronta', 'Pronta para Entrega'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='criada', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text="Campo 'Observação' do formulário físico", verbose_name='Observação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total dos produtos da encomenda', max_digits=10, verbose_name='Valor do Produto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomendas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
                'ordering': ['-numero_encomenda'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(default=django.utils.timezone.now, help_text="Campo 'Data Entrega' do formulário físico", verbose_name='Data Entrega')),
                ('responsavel_entrega', models.CharField(default='A definir', help_text="Campo 'Responsável Entrega' do formulário físico", max_length=100, verbose_name='Responsável Entrega')),
                ('valor_pago_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Campo 'Valor Pago Adiantamento' do formulário físico", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Pago Adiantamento')),
                ('data_entrega_realizada', models.DateField(blank=True, help_text='Data da entrega realizada (seção inferior)', null=True, verbose_name='Data')),
                ('hora_entrega', models.TimeField(blank=True, help_text='Hora da entrega (seção inferior)', null=True, verbose_name='Hora')),
                ('entregue_por', models.CharField(blank=True, help_text="Campo 'Entregue por' da seção inferior", max_length=100, verbose_name='Entregue por')),
                ('assinatura_cliente', models.TextField(blank=True, help_text='Campo para assinatura do cliente', verbose_name='Ass. do Cliente')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista (controle)')),
                ('data_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Realizada (controle)')),
                ('observacoes_entrega', models.TextField(blank=True, verbose_name='Observações da Entrega')),
                ('encomenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encomendas.encomenda', verbose_name='Encomenda')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='ItemEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_cotado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Cotado')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='encomendas.encomenda')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomendas.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomendas.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Encomenda',
                'verbose_name_plural': 'Itens da Encomenda',
            },
        ),
    ]
